version: '3'

services:
 db:
  image: postgres
  restart: always
  env_file: .env
  expose:
   - "${DB_PORT}"
  volumes:
   - "${DATA_PATH}/pgdata:/data/pgdata"
  environment:
   PGDATA: ${DATA_PATH}/pgdata
   POSTGRES_USER: ${DB_USER}
   POSTGRES_PASSWORD: ${DB_PASS}
   POSTGRES_DB: ${DB_NAME}
  container_name: db

 dwarfbot_tg:
  build: .
  restart: always
  env_file: .env
  volumes:
   - "${DATA_PATH}/logs:/code/logs"
   - "${DATA_PATH}/cert:/code/cert"
  expose:
   - "${WEBHOOK_PORT}:${WEBHOOK_PORT}"
  depends_on:
   - db
  links:
   - db
  container_name: telegram-bot
